version: '3.8'
# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  coreai-mcu-generation-oai:
    build:
      target: development
    image: coreai-mcu-generation-oai-development
    container_name: coreai-mcu-generation-oai-development
    ports:
      - "4000:3000"
      - "8000:9229"
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./scripts:/home/node/scripts
      - ./package.json:/home/node/package.json
    environment:
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST:-host.docker.internal}
      GENERATION_REQUEST_OAI_SUBSCRIPTION: ${GENERATION_REQUEST_OAI_SUBSCRIPTION:-coreai-mcu-generation-oai}
      GENERATION_REQUEST_TOPIC: ${GENERATION_REQUEST_TOPIC:-coreai-mcu-generate}${MESSAGE_QUEUE_SUFFIX}
      SUMMARY_REQUEST_TOPIC: ${SUMMARY_REQUEST_TOPIC:-coreai-mcu-triage}${MESSAGE_QUEUE_SUFFIX}
      RESPONSE_PROCESSING_QUEUE_ADDRESS: ${RESPONSE_PROCESSING_QUEUE_ADDRESS:-coreai-mcu-response}${MESSAGE_QUEUE_SUFFIX}
      AZURE_STORAGE_USE_CONNECTION_STRING: ${AZURE_STORAGE_USE_CONNECTION_STRING:-true}
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING:-DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://host.docker.internal:10000/devstoreaccount1;}
      AZURE_STORAGE_ACCOUNT: ${AZURE_STORAGE_ACCOUNT:-devstoreaccount1}
      AZURE_OPENAI_ENABLED: ${AZURE_OPENAI_ENABLED:-true}
      AWS_BEDROCK_ENABLED: ${AWS_BEDROCK_ENABLED:-true}
      OLLAMA_ENABLED: ${OLLAMA_ENABLED:-true}

volumes:
  azurite_data:
