services:
  coreai-mcu-generation-oai:
    build:
      context: .
      target: production
    image: coreai-mcu-generation-oai
    container_name: coreai-mcu-generation-oai
    environment:
      APPINSIGHTS_CLOUDROLE: coreai-mcu-generation-oai-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      GENERATION_REQUEST_OAI_SUBSCRIPTION: ${GENERATION_REQUEST_OAI_SUBSCRIPTION:-coreai-mcu-generation-oai}
      GENERATION_REQUEST_TOPIC: ${GENERATION_REQUEST_TOPIC:-coreai-mcu-generation-request}
      SUMMARY_REQUEST_TOPIC: ${SUMMARY_REQUEST_TOPIC:-coreai-mcu-summary-request}
      RESPONSE_PROCESSING_QUEUE_ADDRESS: ${RESPONSE_PROCESSING_QUEUE_ADDRESS:-coreai-mcu-generation-response}
      POSTGRES_DB: coreai-mcu-knowledge-pgv
      POSTGRES_HOST: ${POSTGRES_HOST:-core-ai-mcu-knowledge-pgv}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}
      POSTGRES_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-ppp}
      AZURE_STORAGE_ACCOUNT: ${AZURE_STORAGE_ACCOUNT:-test}
      AZURE_OPENAI_INSTANCE_NAME: ${AZURE_OPENAI_INSTANCE_NAME:-test}
      AZURE_OPENAI_KEY: ${AZURE_OPENAI_KEY:-test}
      AZURE_OPENAI_API_VERSION: ${AZURE_OPENAI_API_VERSION:-test}
      AWS_BEDROCK_REGION: ${AWS_BEDROCK_REGION:-test}
      AWS_BEDROCK_ACCESS_KEY_ID: ${AWS_BEDROCK_ACCESS_KEY_ID:-test}
      AWS_BEDROCK_SECRET_ACCESS_KEY: ${AWS_BEDROCK_SECRET_ACCESS_KEY:-test}
      AWS_BEDROCK_MAX_TOKENS_TO_SAMPLE: ${AWS_BEDROCK_MAX_TOKENS_TO_SAMPLE:-test}
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL:-http://localhost:11434}
      EMBEDDING_MODEL_NAME: ${EMBEDDING_MODEL_NAME:-test}
      GENERATION_MODEL_NAME: ${GENERATION_MODEL_NAME:-test}
      DOCUMENTS_API_BASE_URL: ${DOCUMENTS_API_BASE_URL:-coreai-mcu-documents}
      RESPONSES_API_BASE_URL: ${RESPONSES_API_BASE_URL:-coreai-mcu-responses}
      PROMPTS_API_BASE_URL: ${PROMPTS_API_BASE_URL:-coreai-mcu-prompts}
      AZURE_OPENAI_ENABLED: ${AZURE_OPENAI_ENABLED:-false}
      OLLAMA_ENABLED: ${OLLAMA_ENABLED:-false}
