services:
  coreai-mcu-generation-oai:
    build:
      context: .
      target: production
    image: coreai-mcu-generation-oai
    container_name: coreai-mcu-generation-oai
    depends_on:
      - coreai-mcu-generation-oai-postgres
      - coreai-mcu-generation-azurite
    environment:
      APPINSIGHTS_CLOUDROLE: coreai-mcu-generation-oai-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      KNOWLEDGE_INGESTION_PGV_SUBSCRIPTION: ${KNOWLEDGE_INGESTION_PGV_SUBSCRIPTION:-coreai-mcu-generation-oai}
      KNOWLEDGE_INGESTION_TOPIC: ${KNOWLEDGE_INGESTION_TOPIC:-coreai-mcu-knowledge-ingestion}
      POSTGRES_DB: coreai-mcu-generation-oai
      POSTGRES_HOST: ${POSTGRES_HOST:-aphw-ddi-api-postgres}
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}
      POSTGRES_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-ppp}
      AZURE_STORAGE_ACCOUNT: ${AZURE_STORAGE_ACCOUNT:-test}
      AZURE_OPENAI_INSTANCE_NAME: ${AZURE_OPENAI_INSTANCE_NAME:-test}
      AZURE_OPENAI_KEY: ${AZURE_OPENAI_KEY:-test}
      AZURE_OPENAI_API_VERSION: ${AZURE_OPENAI_API_VERSION:-test}
      EMBEDDING_MODEL_NAME: ${EMBEDDING_MODEL_NAME:-test}

  coreai-mcu-generation-oai-postgres:
    build:
      context: .
      dockerfile: ./postgres/Dockerfile
    image: coreai-mcu-generation-oai-postgres
    environment:
      POSTGRES_DB: coreai-mcu-generation-oai
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres

  coreai-mcu-generation-azurite:
    image: mcr.microsoft.com/azure-storage/azurite