services:
  coreai-mcu-generation-oai:
    build:
      context: .
      target: production
    image: coreai-mcu-generation-oai
    container_name: coreai-mcu-generation-oai
    depends_on:
      - coreai-mcu-generation-oai-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: coreai-mcu-generation-oai-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
<<<<<<< Updated upstream

  coreai-mcu-generation-oai-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: coreai-mcu-generation-oai
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
=======
      GENERATION_REQUEST_OAI_SUBSCRIPTION: ${GENERATION_REQUEST_OAI_SUBSCRIPTION:-coreai-mcu-generation-oai}
      GENERATION_REQUEST_TOPIC: ${GENERATION_REQUEST_TOPIC:-coreai-mcu-generation-request}
      RESPONSE_PROCESSING_QUEUE_ADDRESS: ${RESPONSE_PROCESSING_QUEUE_ADDRESS:-coreai-mcu-generation-response}
      POSTGRES_DB: ${POSTGRES_DB:-coreai-mcu-knowledge-pgv}
      POSTGRES_HOST: ${POSTGRES_HOST:-core-ai-mcu-knowledge-pgv}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}
      POSTGRES_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-ppp}
      AZURE_STORAGE_ACCOUNT: ${AZURE_STORAGE_ACCOUNT:-test}
      AZURE_OPENAI_KEY: ${AZURE_OPENAI_KEY:-test}
      AZURE_OPENAI_API_VERSION: ${AZURE_OPENAI_API_VERSION:-test}
      AZURE_OPENAI_INSTANCE_NAME: ${AZURE_OPENAI_INSTANCE_NAME:-test}
      AZURE_OPENAI_API_MODEL_NAME_EMBEDDINGS: ${AZURE_OPENAI_API_MODEL_NAME_EMBEDDINGS:-test}
      AZURE_OPENAI_API_DEPLOYMENT_NAME_EMBEDDINGS: ${AZURE_OPENAI_API_DEPLOYMENT_NAME_EMBEDDINGS:-test}
      AZURE_OPENAI_API_MODEL_NAME_GENERATE: ${AZURE_OPENAI_API_MODEL_NAME_GENERATE:-test}
      AZURE_OPENAI_API_DEPLOYMENT_NAME_GENERATE: ${AZURE_OPENAI_API_DEPLOYMENT_NAME_GENERATE:-test}
      AZURE_OPENAI_BASE_PATH: ${AZURE_OPENAI_BASE_PATH:-test}
      AZURE_OPENAI_ENDPOINT: ${AZURE_OPENAI_ENDPOINT:-test}
      EMBEDDING_MODEL_NAME: ${EMBEDDING_MODEL_NAME:-test}
      GENERATION_MODEL_NAME: ${GENERATION_MODEL_NAME:-test}
      DOCUMENTS_API_BASE_URL: ${DOCUMENTS_API_BASE_URL:-test}
      RESPONSES_API_BASE_URL: ${RESPONSES_API_BASE_URL:-test}
>>>>>>> Stashed changes
