# For documentation on how to use, please go here: https://github.com/DEFRA/adp-aso-helm-library?tab=readme-ov-file#adp-platform-azure-service-operator-helm-library-chart.
# You may create Queues, Topics, Subscriptions, Storage Accounts, Databases and Role Assignments on these here.

namespaceTopics:
  - name: generate
    roleAssignments:
      - roleName: 'TopicReceiver'
    topicSubscriptions:
      - name: generation-oai
  - name: triage
    roleAssignments:
      - roleName: 'TopicReceiver'
    topicSubscriptions:
      - name: generation-oai

namespaceQueues:
  - name: responses
    owner: 'no'
    roleAssignments:
      - roleName: 'QueueSender'
