- key: APPINSIGHTS_CONNECTIONSTRING
  value: "{{servicename}}-APPINSIGHTS-CONNECTIONSTRING"
  type: "keyvault"
- key: DOCUMENTS_API_BASE_URL
  value: "http://coreai-mcu-documents.crai-mcu.svc.cluster.local"
- key: RESPONSES_API_BASE_URL
  value: "http://coreai-mcu-responses.crai-mcu.svc.cluster.local"
- key: PROMPTS_API_BASE_URL
  value: "http://coreai-mcu-prompts.crai-mcu.svc.cluster.local"
- key: PERSONAS_API_BASE_URL
  value: "http://coreai-mcu-personas.crai-mcu.svc.cluster.local"
- key: MESSAGE_QUEUE_HOST
  value: "{{servicename}}-MESSAGE-QUEUE-HOST"
  type: "keyvault"
- key: GENERATION_REQUEST_OAI_SUBSCRIPTION
  value: "crai-mcu-generation-oai"
- key: GENERATION_REQUEST_TOPIC
  value: "crai-mcu-generate"
- key: SUMMARY_REQUEST_TOPIC
  value: "crai-mcu-triage"
- key: RESPONSE_PROCESSING_QUEUE_ADDRESS
  value: "crai-mcu-response"
- key: POSTGRES_HOST
  value: "{{servicename}}-POSTGRES-HOST"
  type: "keyvault"
- key: POSTGRES_USERNAME
  value: "{{servicename}}-POSTGRES-USERNAME"
  type: "keyvault"
- key: POSTGRES_DB
  value: "crai-mcu-knowledge"
- key: POSTGRES_PORT
  value: "5432"
- key: AZURE_OPENAI_ENABLED
  value: "true"
- key: AZURE_OPENAI_INSTANCE_NAME
  value: "{{servicename}}-AZURE-OPENAI-INSTANCE-NAME"
  type: "keyvault"
- key: AZURE_OPENAI_KEY
  value: "{{servicename}}-AZURE-OPENAI-KEY"
  type: "keyvault"
- key: AZURE_OPENAI_API_VERSION
  value: "2024-02-01"
- key: AWS_BEDROCK_ENABLED
  value: "true"
- key: AWS_BEDROCK_REGION
  value: "{{servicename}}-AWS-BEDROCK-REGION"
  type: "keyvault"
- key: AWS_BEDROCK_ACCESS_KEY_ID
  value: "{{servicename}}-AWS-BEDROCK-ACCESS-KEY-ID"
  type: "keyvault"
- key: AWS_BEDROCK_SECRET_ACCESS_KEY
  value: "{{servicename}}-AWS-BEDROCK-SECRET-ACCESS-KEY"
- key: AWS_BEDROCK_MAX_TOKENS_TO_SAMPLE
  value: "{{servicename}}-AWS-BEDROCK-MAX-TOKENS-TO-SAMPLE"
  type: "keyvault"
- key: EMBEDDING_MODEL_NAME
  type: "keyvault"
  value: "{{servicename}}-EMBEDDING-MODEL-NAME"
- key: GENERATION_MODEL_NAME
  type: "keyvault"
  value: "{{servicename}}-GENERATION-MODEL-NAME"
